<template>
  <AppLayout>
    <div class="mx-auto max-w-6xl p-4 md:p-6">
      <header class="mb-5 flex items-center justify-between gap-4"><h1 class="m-0 text-2xl font-bold text-gray-900 dark:text-white">{{ t('admin.upstreamBalances.title') }}</h1><div class="flex items-center gap-2"><button class="btn btn-secondary h-9 w-9 !p-0" :disabled="loading" :title="t('common.refresh')" @click="refresh"><Icon name="refresh" size="sm" :class="loading ? 'animate-spin' : ''" /></button><button class="btn btn-primary" @click="openCreate"><Icon name="plus" size="sm" />{{ t('admin.upstreamBalances.add') }}</button></div></header>
      <div v-if="error" class="mb-4 flex items-start gap-3 rounded-lg border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700 dark:border-red-900/40 dark:bg-red-900/20 dark:text-red-300"><Icon name="exclamationTriangle" size="sm" class="mt-0.5 shrink-0" /><span>{{ error }}</span></div>
      <div v-if="loading && items.length === 0" class="rounded-lg border border-gray-200 bg-white py-16 text-center text-sm text-gray-500 shadow-sm dark:border-dark-600 dark:bg-dark-800"><Icon name="refresh" size="lg" class="mx-auto mb-3 animate-spin text-primary-500" /><p>{{ t('common.loading') }}</p></div>
      <div v-else-if="!loading && items.length === 0" class="rounded-lg border border-dashed border-gray-300 bg-white py-16 text-center text-sm text-gray-500 dark:border-dark-600 dark:bg-dark-800">{{ t('admin.upstreamBalances.empty') }}</div>
      <section v-else class="overflow-hidden rounded-lg border border-gray-200 bg-white shadow-sm dark:border-dark-600 dark:bg-dark-800">
        <div v-for="item in items" :key="item.base_url" class="grid min-h-[88px] grid-cols-[minmax(0,1.15fr)_minmax(220px,.9fr)_auto_auto] items-center gap-6 border-b border-gray-100 px-4 py-3 last:border-b-0 dark:border-dark-700 max-lg:grid-cols-[minmax(0,1fr)_auto_auto] max-md:grid-cols-1 max-md:gap-2">
          <div class="min-w-0"><a :href="item.base_url" target="_blank" rel="noreferrer" class="flex min-w-0 items-center gap-2 truncate font-mono text-[13px] font-semibold text-primary-600 hover:underline dark:text-primary-400"><Icon name="link" size="sm" class="shrink-0" /><span class="truncate">{{ item.base_url }}</span></a><div class="mt-0.5 pl-6 text-[11px] text-gray-400 dark:text-gray-500">{{ t('admin.upstreamBalances.lastSynced', { time: formatTime(item.last_synced_at) }) }}</div></div>
          <div class="min-w-0 max-lg:col-span-2 max-md:col-span-1"><div class="mb-1 text-[11px] text-gray-400">{{ t('admin.upstreamBalances.groups') }}</div><div class="flex flex-wrap gap-1.5"><span v-for="name in item.group_names" :key="name" class="rounded border border-primary-100 bg-primary-50 px-2 py-0.5 text-xs font-medium text-primary-700 dark:border-primary-900/40 dark:bg-primary-900/20 dark:text-primary-300">{{ name }}</span><span v-if="!item.group_names?.length" class="text-xs text-gray-400">{{ t('admin.upstreamBalances.noGroups') }}</span></div></div>
          <div class="whitespace-nowrap text-sm text-gray-700 dark:text-gray-200">{{ t('admin.upstreamBalances.remaining') }}<b class="ml-1.5 text-base text-gray-900 dark:text-white">{{ formatBalance(item) }}</b></div>
          <div class="flex items-center gap-1"><button class="icon-btn" :title="t('admin.upstreamBalances.edit')" @click="openEdit(item)"><Icon name="edit" size="sm" /></button><button class="icon-btn text-red-500 hover:text-red-600" :title="t('admin.upstreamBalances.delete')" @click="remove(item)"><Icon name="trash" size="sm" /></button></div>
        </div>
      </section>
    </div>
    <div v-if="modalOpen" class="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4" @click.self="modalOpen = false"><form class="w-full max-w-lg rounded-lg bg-white shadow-xl dark:bg-dark-800" @submit.prevent="save"><div class="flex items-center justify-between border-b border-gray-200 px-5 py-4 dark:border-dark-600"><h2 class="text-lg font-semibold text-gray-900 dark:text-white">{{ editing ? t('admin.upstreamBalances.edit') : t('admin.upstreamBalances.add') }}</h2><button type="button" class="icon-btn" @click="modalOpen = false"><Icon name="x" size="sm" /></button></div><div class="grid gap-4 px-5 py-5"><label class="block"><span class="mb-1.5 block text-sm font-medium">{{ t('admin.upstreamBalances.baseUrl') }}</span><input v-model="form.base_url" required class="input w-full" placeholder="https://api.example.com" /></label><label class="block"><span class="mb-1.5 block text-sm font-medium">{{ t('admin.upstreamBalances.name') }}</span><input v-model="form.name" class="input w-full" /></label><label class="block"><span class="mb-1.5 block text-sm font-medium">{{ t('admin.upstreamBalances.apiKey') }}<small v-if="editing" class="ml-1 text-gray-400">({{ t('admin.upstreamBalances.optional') }})</small></span><input v-model="form.api_key" type="password" :required="!editing" class="input w-full" autocomplete="new-password" /></label><label class="block"><span class="mb-1.5 block text-sm font-medium">{{ t('admin.upstreamBalances.groups') }}</span><select v-model="form.group_ids" multiple class="input min-h-28 w-full"><option v-for="group in groups" :key="group.id" :value="group.id">{{ group.name }}</option></select></label></div><div class="flex justify-end gap-2 border-t border-gray-200 px-5 py-4 dark:border-dark-600"><button type="button" class="btn btn-secondary" @click="modalOpen = false">{{ t('common.cancel') }}</button><button class="btn btn-primary" :disabled="saving">{{ saving ? t('common.saving') : t('common.save') }}</button></div></form></div>
  </AppLayout>
</template>
<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { useI18n } from 'vue-i18n'
import AppLayout from '@/components/layout/AppLayout.vue'
import Icon from '@/components/icons/Icon.vue'
import { adminAPI } from '@/api'
import type { AdminGroup } from '@/types'
import type { UpstreamBalanceOverviewItem } from '@/api/admin/upstreamBalances'
const { t } = useI18n(); const items = ref<UpstreamBalanceOverviewItem[]>([]); const groups = ref<AdminGroup[]>([]); const loading = ref(false); const saving = ref(false); const error = ref(''); const modalOpen = ref(false); const editing = ref<UpstreamBalanceOverviewItem | null>(null); const form = ref({ base_url: '', name: '', api_key: '', group_ids: [] as number[] })
function formatBalance(item: UpstreamBalanceOverviewItem): string { if (typeof item.balance !== 'number') return t('admin.upstreamBalances.unavailable'); const amount = new Intl.NumberFormat(undefined, { maximumFractionDigits: 4 }).format(item.balance); return item.unit === 'USD' ? `US$ ${amount}` : item.unit ? `${item.unit} ${amount}` : amount }
function formatTime(value?: string): string { return value ? new Date(value).toLocaleString() : t('admin.upstreamBalances.unavailable') }
async function refresh() { loading.value = true; error.value = ''; try { items.value = await adminAPI.upstreamBalances.refresh() } catch (reason: any) { error.value = reason?.response?.data?.message || reason?.response?.data?.detail || reason?.message || t('admin.upstreamBalances.loadFailed') } finally { loading.value = false } }
function openCreate() { editing.value = null; form.value = { base_url: '', name: '', api_key: '', group_ids: [] }; modalOpen.value = true }
function openEdit(item: UpstreamBalanceOverviewItem) { editing.value = item; form.value = { base_url: item.base_url, name: '', api_key: '', group_ids: [...(item.group_ids || [])] }; modalOpen.value = true }
async function save() { saving.value = true; try { const payload = { ...form.value, group_ids: form.value.group_ids.map(Number) }; if (editing.value) await adminAPI.upstreamBalances.update(editing.value.account_id, payload); else await adminAPI.upstreamBalances.create(payload); modalOpen.value = false; await refresh() } catch (reason: any) { error.value = reason?.response?.data?.detail || reason?.response?.data?.message || reason?.message || t('admin.upstreamBalances.saveFailed') } finally { saving.value = false } }
async function remove(item: UpstreamBalanceOverviewItem) { if (!window.confirm(t('admin.upstreamBalances.deleteConfirm'))) return; try { await adminAPI.upstreamBalances.remove(item.account_id); await refresh() } catch (reason: any) { error.value = reason?.response?.data?.detail || reason?.message || t('admin.upstreamBalances.deleteFailed') } }
onMounted(async () => { try { groups.value = await adminAPI.groups.getAllIncludingInactive() } catch { groups.value = [] } await refresh() })
</script>
