export const authCopy = {
  zh: {
    home: '返回首页',
    loginLabel: '账号登录',
    registerLabel: '邮箱注册',
    verifyLabel: '邮箱验证',
    loginTitle: '欢迎回来',
    registerTitle: '创建你的账号',
    verifyTitle: '确认你的邮箱',
    loginDescription: '登录账户，继续你的 AI 工作。',
    registerDescription: '从一个账号开始，连接你常用的 AI 服务。',
    verifyDescription: '完成邮箱验证后，即可创建账号。',
    email: '邮箱地址',
    emailPlaceholder: '输入你的邮箱',
    registerEmailPlaceholder: 'QQ 邮箱或 Gmail',
    emailHint: '支持 QQ 邮箱和 Gmail',
    password: '密码',
    passwordPlaceholder: '输入你的密码',
    newPassword: '设置密码',
    newPasswordPlaceholder: '至少 6 位字符',
    passwordHint: '至少 6 位，建议混合字母、数字和符号。',
    showPassword: '显示密码',
    hidePassword: '隐藏密码',
    capsLock: '大写锁定已开启',
    forgot: '忘记密码？',
    login: '登录',
    continue: '下一步，验证邮箱',
    noAccount: '还没有账号？',
    createAccount: '立即注册',
    hasAccount: '已有账号？',
    signIn: '前往登录',
    accountStep: '填写信息',
    verifyStep: '验证邮箱',
    editEmail: '修改邮箱',
    code: '邮箱验证码',
    codePlaceholder: '6 位数字验证码',
    sendCode: '发送验证码',
    verify: '验证并创建账号',
    backToRegister: '返回填写信息',
    emailRequired: '请输入邮箱地址。',
    emailInvalid: '请输入有效的邮箱地址。',
    emailUnsupported: '注册目前支持 QQ 邮箱和 Gmail。',
    passwordRequired: '请输入密码。',
    passwordShort: '密码至少需要 6 位字符。',
    codeInvalid: '请输入 6 位数字验证码。',
    previewLogin: '本地预览暂未接入登录服务，你填写的信息未提交。',
    previewEmail: '本地预览暂未发送邮件。',
    previewSend: '本地预览暂未接入邮件服务，未发送验证码。',
    previewRegister: '本地预览暂未接入注册服务，未创建账号。',
    support: '联系站长',
    recoverTitle: '找回你的账号',
    recoverDescription: '忘记登录密码？通过微信联系站长，协助处理账号问题。',
    supportDescription: '账号或服务遇到问题，通过微信联系站长。',
    scan: '微信扫码联系',
    copyWechat: '复制微信号',
    copied: '已复制',
    copyFailed: '请选中微信号手动复制。',
    close: '关闭',
    services: ['模型 API', 'AI 订阅', '短信接码'],
  },
  en: {
    home: 'Back to home',
    loginLabel: 'SIGN IN',
    registerLabel: 'GET STARTED',
    verifyLabel: 'EMAIL VERIFICATION',
    loginTitle: 'Welcome back',
    registerTitle: 'Create your account',
    verifyTitle: 'Confirm your email',
    loginDescription: 'Sign in and get back to your AI work.',
    registerDescription: 'One account to connect with the AI you use.',
    verifyDescription: 'Verify your email to finish creating your account.',
    email: 'Email address',
    emailPlaceholder: 'Enter your email',
    registerEmailPlaceholder: 'QQ Mail or Gmail address',
    emailHint: 'QQ Mail and Gmail are supported',
    password: 'Password',
    passwordPlaceholder: 'Enter your password',
    newPassword: 'Create a password',
    newPasswordPlaceholder: 'At least 6 characters',
    passwordHint: 'At least 6 characters. Mix letters, numbers, and symbols.',
    showPassword: 'Show password',
    hidePassword: 'Hide password',
    capsLock: 'Caps Lock is on',
    forgot: 'Forgot password?',
    login: 'Sign in',
    continue: 'Continue to verification',
    noAccount: 'New here?',
    createAccount: 'Create an account',
    hasAccount: 'Already have an account?',
    signIn: 'Sign in',
    accountStep: 'Account details',
    verifyStep: 'Verify email',
    editEmail: 'Edit email',
    code: 'Email verification code',
    codePlaceholder: '6-digit code',
    sendCode: 'Send code',
    verify: 'Verify and create account',
    backToRegister: 'Back to account details',
    emailRequired: 'Enter your email address.',
    emailInvalid: 'Enter a valid email address.',
    emailUnsupported: 'Registration currently supports QQ Mail and Gmail.',
    passwordRequired: 'Enter your password.',
    passwordShort: 'Use at least 6 characters.',
    codeInvalid: 'Enter a 6-digit verification code.',
    previewLogin:
      'Sign-in is not connected in this local preview. Your details have not been submitted.',
    previewEmail: 'No email has been sent in this local preview.',
    previewSend:
      'Email delivery is not connected in this local preview. No code has been sent.',
    previewRegister:
      'Registration is not connected in this local preview. No account has been created.',
    support: 'Contact support',
    recoverTitle: 'Recover your account',
    recoverDescription:
      'Forgot your password? Contact us on WeChat for help with your account.',
    supportDescription:
      'For help with your account or services, contact us on WeChat.',
    scan: 'Scan with WeChat',
    copyWechat: 'Copy WeChat ID',
    copied: 'Copied',
    copyFailed: 'Select the WeChat ID and copy it manually.',
    close: 'Close',
    services: ['Model API', 'AI subscriptions', 'SMS codes'],
  },
}
